processed_df_cache: "data/processed_df.pkl"
use_cache: True
spacy_language_model: de_core_news_lg
# spacy_language_model: de_core_news_sm
relevant_scoring_pos:
  - ADJ
  - ADV
  - NOUN
  - VERB
# relevant_scoring_tags:
#   - ADJA
#   - ADJD
#   - ADV
#   - ITJ
#   - NN
#   - PTKVZ
#   - PTKANT
#   - VVFIN
#   - VAFIN
#   - VMFIN
#   - VVINF
#   - VAINF
#   - VMINF
#   - VVIMP
#   - VAIMP
#   - VVPP
#   - VAPP
#   - VMPP
#   - VVIZU
party_colors:
  CDU/CSU: black
  SPD: red
  Grüne: green
  FDP: yellow
  PDS: magenta
  DIE LINKE.: magenta
  AfD: lightblue
  Fraktionslos: lightgrey
  DRP/NR: lightgrey
  KO: lightgrey
  SSW: lightgrey
  WAV: lightgrey
  BHE: lightgrey
  DPB: lightgrey
  FU: lightgrey
  FVP: lightgrey
  BP: lightgrey
  NR: lightgrey
  DA: lightgrey
  not found: lightgrey
