# -*- coding: utf-8 -*-

# TOPIC: ANTI NUCLEAR
# Is <keyword> helping to leave nuclear energy (in a sustainable manner)? If yes, the topic fits here.
ANTI_NUCLEAR = [
    "Atomausstieg",
    "Atomausstieges",
    "EEG",
    "EEG-Reform",
    "EEG-Umlage",
    "Energieleitungsausbaugesetz",
    "Energierevolution",
    "Energiespeicherung",
    "Energiewende",
    "Erdgasförderung",
    "Erneuerbare-Energien-Gesetz",
    "Erneuerbare-Energien-Gesetzes",
    "Gaskraftwerk",
    "Gaskraftwerke",
    "Gaskraftwerkes",
    "Gaskraftwerken",
    "Kernenergiegegner",
    "Kraft-Wärme-Kopplung",
    "Kraft-Wärme-Kopplungsgesetz",
    "KWK",
    "KWK-Gesetz",
    "KWKG",
    "Netzstabilität",
    "Onshorewindenergie",
    "Solaranlage",
    "Solaranlagen",
    "Solarenergie",
    "Solarstrom",
    "Solarstromes",
    "Solarzelle",
    "Solarzellen",
    "Sonnenenergie",
    "Speichermöglichkeit",
    "Speichermöglichkeiten",
    "Speichertechnologie",
    "Speichertechnologien",
    "Trassenausbau",
    "Wasserkraft",
    "Windenergie",
    "Ökostrom",
]

# TOPIC: PRO NUCLEAR
# Is <keyword> helping to keep nuclear energy? If yes, the topic fits here.
PRO_NUCLEAR = [
    "AKW",
    "AKWs",
    "Atomanlage",
    "Atomanlagen",
    "Atomaufsicht",
    "Atomenergie",
    "Atomenergiebehörde",
    "Atomforschung",
    "Atomgesetz",
    "Atomgesetzes",
    "Atomindustrie",
    "Atomkraftwerk",
    "Atomkraftwerke",
    "Atomkraftwerkes",
    "Atomlobby",
    "Atommüll",
    "Atomreaktor",
    "Atomreaktoren",
    "Atomreaktores",
    "Atomsicherheit",
    "Atomwirtschaft",
    "Brennelement",
    "Brennstäbe",
    "Endlager",
    "Endlagerung",
    "Euratom",
    "Euratom-Vertrag",
    "Kernenergie",
    "Kernenergielobby",
    "Kernenergiewirtschaft" "Kernkraft",
    "Kernkraftwerk",
    "Kernkraftwerke",
    "Kernkraftwerkes",
    "Kernreaktor",
    "Kernreaktoren",
    "Kernreaktors",
    "Laufzeitverlängerung",
    "Nuklearenergiekommission",
    "Nuklearmaterial",
    "Reaktor",
    "Reaktoren",
    "Reaktors",
    "Reaktorsicherheit",
    "Zwischenlagerung",
]

# TOPIC: CONSERVATIVE ENERGY
# Is <keyword> associated with conservative energy and does not fit into the above categories?
CONSERVATIVE_ENERGY = [
    "Braunkohlekraftwerk",
    "Braunkohlekraftwerke",
    "Braunkohlestrom",
    "Braunkohleverstromung",
    "Einspeisevergütung",
    "Energiepreis",
    "Energiepreise",
    "Energiesparen",
    "Energiesparpotenzial",
    "Energiestrategie",
    "Kohle",
    "Kohlen",
    "Kohleausstieg" "Kohlekraftwerk",
    "Kohlekraftwerke",
    "Kohlekraftwerks",
    "Kohlelobby",
    "Netzbetreiber",
    "Primärenergie",
    "Steinkohlebergbau",
]

# TOPIC: NEUTRAL ENERGY
# Is <keyword> directly associated with energy politics but does not fit into the above categories?
NEUTRAL_ENERGY = [
    "Brückentechnologie",
    "Brückentechnologien",
    "Emissionshandel",
    "Energie",
    "Energieeffizienz",
    "Energiemix",
    "Energiemixes",
    "Energiepolitik",
    "Energieprogramm",
    "Energiequelle",
    "Energiequellen",
    "Energiesteuer",
    "Energietechnologie",
    "Energietechnologien",
    "Energieunternehmen",
    "Energieversorgungsunternehmen",
    "Energiewirtschaft",
    "Energiewirtschaftsgesetz",
    "Erdverkabelung",
    "Kraftwerkbetreiber",
    "Kraftwerksbetreiber",
    "Netzentgelt",
    "Netzentgelte",
    "Strom",
    "Stromerzeugung",
    "Stromproduktion",
    "Versorgungssicherheit",
    "Überbrückungstechnologie",
    "Überbrückungstechnologien",
    "Übergangszeit",
]
